Changed requirements.txt to include code specific dependency pyyaml a…
rohzb/hzb-bii-emcgw pull request #1
Opened 2023-10-19 09:44 UTC by rawafb

…nd check in bootsrap if venv module is installed

2023-10-20 15:17 UTC, rohzb requested changes

2023-10-20 17:59 UTC, rawafb commented on scripts/bootstrap.sh
I've addressed the feedback provided. Please take a look!

2023-10-21 15:27 UTC, rohzb approved these changes
Looks good!

2023-10-21 15:28 UTC, merged

2023-10-21 15:28 UTC, rohzb commented
Updates from Andreas correcting installation issues on a clean debian system