Handle the situation when an attempt to bind a socket to a specific I…
rohzb/hzb-bii-emcgw pull request #2
Opened 2023-12-01 16:32 UTC by rawafb

…P address and port fails during startup. Provide an error message for the user.

2023-12-02 05:31 UTC, rohzb requested changes
Cool!

1 change is required - use `logger` already imported instead importing logging. It sets extra verbosity levels and allow enable/disable printing of them over command line options - see comments to particular line

2023-12-02 05:31 UTC, rohzb commented on src/emcgw/server.py
> +import logging
do not `import logging`, use `logger `above - that way we can use command line options for extra verbosity.

2023-12-02 05:31 UTC, rohzb commented on src/emcgw/server.py
> +            logging.error(f"Failed to bind to {self.local_host}:{self.local_port} - {e}")
same here: it should be `logger `instead of `logging`

2023-12-03 08:48 UTC, rawafb commented on src/emcgw/server.py
> +import logging
Done!

2023-12-03 09:35 UTC, merged